### ISSUE TITLE
Crash when screen orietation changed while slide to arm is displaying 

### ISSUE THREAD

**Issue by TShapinsky** [DroidPlanner/Tower#1558]
this is on the develop branch
`08-06 10:53:36.028    1106-1106/org.droidplanner.android.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.droidplanner.android.debug, PID: 1106
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.droidplanner.android.debug/org.droidplanner.android.activities.FlightActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment org.droidplanner.android.dialogs.SlideToUnlockDialog$1: make sure class name exists, is public, and has an empty constructor that is public
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment org.droidplanner.android.dialogs.SlideToUnlockDialog$1: make sure class name exists, is public, and has an empty constructor that is public
            at android.support.v4.app.Fragment.instantiate(Fragment.java:436)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1835)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1778)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1924)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1779)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1924)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:268)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:58)
            at org.droidplanner.android.activities.helpers.SuperUI.onCreate(SuperUI.java:82)
            at org.droidplanner.android.activities.DrawerNavigationUI.onCreate(DrawerNavigationUI.java:66)
            at org.droidplanner.android.activities.FlightActivity.onCreate(FlightActivity.java:195)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalAccessException: class org.droidplanner.android.dialogs.SlideToUnlockDialog$1 is not accessible from class android.support.v4.app.Fragment
            at java.lang.Class.newInstance(Class.java:1591)
            at android.support.v4.app.Fragment.instantiate(Fragment.java:421)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1835)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1778)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1924)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1779)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1924)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:268)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:58)
            at org.droidplanner.android.activities.helpers.SuperUI.onCreate(SuperUI.java:82)
            at org.droidplanner.android.activities.DrawerNavigationUI.onCreate(DrawerNavigationUI.java:66)
            at org.droidplanner.android.activities.FlightActivity.onCreate(FlightActivity.java:195)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by ne0fhyk** [comment]
Fixed by commit 69a28a9
