### ISSUE TITLE
[Code bug]java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Linjieqiang** [DroidPlanner/Tower#1690]
Process: org.droidplanner.android.debug, PID: 10181
java.lang.NoClassDefFoundError: org.droidplanner.android.proxy.mission.MissionProxy$1
at org.droidplanner.android.proxy.mission.MissionProxy.<init>(MissionProxy.java:69)
at org.droidplanner.android.DroidPlannerApp.onCreate(DroidPlannerApp.java:151)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4355)
at android.app.ActivityThread.access$1500(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5028)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
at dalvik.system.NativeStart.main(Native Method)

When I running the newer code that build with "0b78b1d" in "develop"branch,it will also melt.

**Comment by wiistriker** [comment]
How do you solve this issue?
